sudo: false
language: generic
cache:
    apt: true
addons:
    apt:
        sources:
            - avsm
        packages:
            - ocaml
            - opam
env:
    - OPAMYES=1 OPAMVERBOSE=1
before_install:
    - ocaml -version
    - opam --version
install:
    - opam init
    - opam install ocamlfind menhir
    - eval `opam config env`
script:
    - make test
